[package]
name = "solana-signer"
description = "Solana abstractions and implementations for transaction signers."
documentation = "https://docs.rs/solana-signer"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bs58 = { workspace = true, features = ["std"] }
ed25519-dalek = { workspace = true }
itertools = { workspace = true }
rand0-7 = { workspace = true }
serde_json = { workspace = true }
solana-pubkey = { workspace = true }
solana-signature = { workspace = true }
solana-transaction-error = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
static_assertions = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
